image: fedora:latest
include:
  - component: gitlab.gnome.org/GNOME/citemplates/release-service@master
    inputs:
      job-stage: release
      dist-job-name: "build-release-tarball"
      tarball-artifact-path: "${TARBALL_ARTIFACT_PATH}"

stages:
  - build
  - release

variables:
  DEPENDENCIES: desktop-file-utils
                gettext
                gcc-c++
                gtkmm4.0-devel
                itstool
                libadwaita-devel
                libsecret-devel
                libuuid-devel
                libxml2-devel
                libxslt-devel
                meson
                pcre-devel
                yelp-tools

  GIT_SUBMODULE_STRATEGY: normal
  MESON_BUILD_DIR: _build
  TARBALL_ARTIFACT_PATH: "${MESON_BUILD_DIR}/meson-dist/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.xz"

build-release-tarball:
  stage: build
  before_script:
    - dnf update -y --nogpgcheck
    - dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    - meson setup "${MESON_BUILD_DIR}"
    - meson test -C "${MESON_BUILD_DIR}"
    - ninja -C "${MESON_BUILD_DIR}" install
    - meson dist -C "${MESON_BUILD_DIR}"
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    when: always
    paths:
      - "${TARBALL_ARTIFACT_PATH}"
