image: fedora:latest

variables:
  DEPENDENCIES: desktop-file-utils
                gettext
                gcc-c++
                gtkmm4.0-devel
                itstool
                libadwaita-devel
                libsecret-devel
                libuuid-devel
                libxml2-devel
                libxslt-devel
                meson
                pcre-devel
                yelp-tools

  GIT_SUBMODULE_STRATEGY: normal
  MESON_BUILD_DIR: _build

build:
  before_script:
    - dnf update -y --nogpgcheck
    - dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    - meson setup "${MESON_BUILD_DIR}"
    - meson test -C "${MESON_BUILD_DIR}"
    - ninja -C "${MESON_BUILD_DIR}" install
