.TH GNOTE 1 "April 7, 2009" gnome "GNOME User's Manuals"
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)

.SH NAME
gnote \- A simple note-taking application for Gnome

.SH SYNOPSIS
.B gnote
.I "[OPTION] ..."

.SH "DESCRIPTION"
This manual page documents briefly the
.BR gnote
command.
.\"Instead, it has documentation in the GNU Info format; see below.
.PP
.B Gnote
is a desktop note-taking application for Linux and Unix. Simple and
easy to use, but with potential to help you organize the ideas and
information you deal with every day.
.PP
Gnote's usefulness lies in the ability to relate notes and ideas
together, using a WikiWiki-like linking system.
.PP
When run without any options, either a Search All Notes window or
the Gnote note menu appears in the notification tray area
depending on configuration.  Selecting a note from a list in
Search All Notes or from the menu from notification area displays
the note's spatial window.
.PP
Changes to notes are saved automatically.  Links to URLs, files, and
other notes are detected as you type.  Rich editing such as
highlighting, bold, italics, undo/redo, and variable font sizes are
supported.
.PP
Global keybindings exist to allow fast access to Gnote notes and
dialogs.  These keybindings are set in GSettings (see below) and may
be activated from any application.

.SH OPTIONS
The program follows the usual GNU command line syntax, with
options starting with two dashes (`--').
A summary of options are included below.
.\"For a complete description, see the Info files.
.TP
.B \-\-background
Run Gnote in background.
.TP
.B \-\-help
Show summary of options.
.TP
.B \-\-highlight-search TEXT
Search and highlight TEXT in the opened note.
.TP
.B \-\-note-path PATH
Specify the path of the directory containing the notes.
.TP
.B \-\-new-note
Create and display a new note.
.TP
.B \-\-new-note TITLE
Create and display a new note with the title given.
.TP
.B \-\-new-window
Open a new window.
.TP
.B \-\-open-note TITLE/URL
Display the existing note matching TITLE or URL.
.TP
.B \-\-search
Open the search all notes window with the search text.
.TP
.B \-\-shell-search
Run Gnote as GNOME Shell search provider.
.TP
.B \-\-start-here
Display the "Start Here" note.
.TP
.B \-\-version
Show version of program.

.SH "GSETTINGS SETTINGS"
Gnote has several preference settings stored in GSettings.  Changes
to Settings are applied instantly to any running Gnote instance. You
can use DConf-Editor to view all settings and see their descriptions.

.SH "SEE ALSO"
.I https://wiki.gnome.org/Apps/Gnote

.SH BUGS
Please enter bug reports in the Gnome Bugzilla
bug tracker (http://bugzilla.gnome.org/enter_bug.cgi?product=Gnote).

.SH AUTHORS
Hubert Figuiere <hub@figuiere.net>
.TP
Debarshi Ray <debarshir@src.gnome.org>
.TP
Aurimas Cernius <aurisc4@gmail.com>

This manual page was originally written by Luca Capello <luca@pca.it>.
Adapted to Gnote by Hubert Figuiere and Aurimas Cernius
